services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root 
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "postgres-db-volume:/var/lib/postgresql/data"
    networks:
      - pg-network
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    networks:
      - pg-network
    ports:
      - "8080:80"
volumes:
    postgres-db-volume:
      external: true
networks:
  pg-network:
    external: true